name: vivapaso
favicon: null
layout_spectrum: 0.09058556612581015
typography_spectrum: 0.24633534206077456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ee3157'
    - '#f26d88'
    - '#f9c0cb'
    - '#555655'
  brandStrength: 0
  lightness: 0.1797448731958866
  saturation: 0.25
  rhythmicContrast: 0.3049408479128033
purpose: []
